Added exemption field to invoices doc
processout/documentation pull request #56
Opened 2020-10-15 14:44 UTC by matt-ridgway-cko

As part of our work to allow exemption codes for 3DS2, we have updated our API documentation to reflect a new optional field, which can be used to indicate the exemption reason when creating an invoice.

This will be merged and deployed when the rest of the work is ready to be deployed.

2020-11-26 11:55 UTC, roshan-gorasia-cko commented
Updates since Matt's initial PR:

- Updated field to be: `exemption_reason_3ds2` instead of `exemptionreason_3ds2`
- Updated values to be e.g: `low-value`

2020-11-30 10:59 UTC, pierre-lafanechaire-cko requested changes

2020-11-30 10:59 UTC, pierre-lafanechaire-cko commented on source/refs/content/payments/_invoices.md.erb
> +<span class="console-font">**exemption_reason_3ds2**</span><br />*string* | Optional reason for requesting 3DS2 not to be invoked (Note: Must also be supported by the PSP)<br /><span style="opacity:
```suggestion
<span class="console-font">**exemption_reason_3ds2**</span><br />*string* | Optional reason for requesting 3DS2 not to be invoked (Note: Must also be supported by the PSP. Please contact our support to know more!)<br /><span style="opacity: 0.5">Allowed values are: "low-value", "trusted-beneficiary" or "transaction-risk-analysis"</span>
```

2020-11-30 10:59 UTC, pierre-lafanechaire-cko approved these changes

2020-11-30 10:59 UTC, merged